-- DROP TABLE IF EXISTS rooms;
-- DROP TABLE IF EXISTS room_users;
CREATE TABLE IF NOT EXISTS rooms (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	start_time TIMESTAMP,
	end_time TIMESTAMP,
	is_timer_running BOOLEAN DEFAULT FALSE
);

INSERT INTO
	rooms (name)
SELECT
	'original'
WHERE
	NOT EXISTS (
		SELECT
			1
		FROM
			rooms
		WHERE
			name = 'original'
	);

CREATE TABLE IF NOT EXISTS room_users (
	room_id UUID NOT NULL,
	username VARCHAR(50) NOT NULL,
	PRIMARY KEY (room_id, username),
	FOREIGN KEY (room_id) REFERENCES rooms(id),
	FOREIGN KEY (username) REFERENCES users(username)
);

CREATE TABLE IF NOT EXISTS booking_records (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	room_id UUID NOT NULL,
	start_time TIMESTAMP,
	end_time TIMESTAMP,
	FOREIGN KEY (room_id) REFERENCES rooms(id)
);